spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: suiyu123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: online.suiyu.basicdemo.model