server:
  port: 7001
eureka:
  instance:
    hostname: localhost #eureka服务端实例名称
  client:
    register-with-eureka: false #是否向注册中心注册自己
    fetch-registry: false #false表示本就是注册中心，职责就是维护服务实例，而非检索服务
    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/ #请求地址