server:
  port: 7003
eureka:
  instance:
    hostname: eureka3-server.com
  client:
    register-with-eureka: false
    fetch-registry: false
    # eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/
    service-url:
      defaultZone: http://eureka2-server.com:7002/eureka/,http://eureka1-server.com:7001/eureka/