server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: suiyu
    url: jdbc:mysql://localhost:3306/school
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 200
      max-total: 5
  redis:
    host: localhost
    port: 6379
  application:
    name: eureka-client1


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: online.suiyu.eurekaclient1.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  path: logs/
eureka:
  client:
    service-url:
      defaultZone: http://eureka1-server.com:7001/eureka/,http://eureka2-server.com:7002/eureka/,http://eureka3-server.com:7003/eureka/
  instance:
    instance-id: micro-client:8081
    prefer-ip-address: true