server:
  port: 7001
spring:
  application:
    name: peer1
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer1:${server.port}/eureka/