server:
  port: 8001
spring:
  application:
    name: eureka-client
  datasource:
    username: root
    password: yuluo
    url: jdbc:mysql://localhost:3306/school?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 200
      max-total: 5

user:
  name: yuluo
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: online.yuluo.entiry.UserInfoVO