server:
  port: 7001

spring:
  application:
    name: eureka-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xiaozheng243/Java-rebuild/
#          search-paths: practice/springboot/eureka-cluster/eureka-server/config-repo/
#          username: xiaozheng243
#          password: ******
#          default-label: master
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/